name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths: 
     - 'BE_Webshop/**'

env:
  JAR_FILE_NAME: 'TaeDeploySNAPSHOT2.jar'
  TARGET_PATH : 'BE'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Build JAR
      run: mvn package -DskipTests
    
    - name: Rename JAR
      run: |
        mv target/Shopping-0.0.1-SNAPSHOT.jar target/${{ env.JAR_FILE_NAME }}
    
    - name: Copy JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: 'BE/target/${{ env.JAR_FILE_NAME }}'
        target: '${{ env.TARGET_PATH }}'
        
    - name: Deployding ... 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo kill -9 $(sudo netstat -plten | grep java | awk '{print $9}' | cut -d '/' -f1)
          tmux kill-session -t deployment
          cd BE/target
          tmux new-session -d -s deployment 'java -jar TaeDeploySNAPSHOT2.jar'
